---
- name: installation of .net core on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: download dotnet core
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
        dest: /tmp/packages-microsoft-prod.rpm
    - name: download package
      ansible.builtin.yum: 
        name: /tmp/packages-microsoft-prod.rpm
    - name: install dotnet core
      ansible.builtin.yum:
        name: dotnet-sdk-7.0
        update_cache: yes
        state: present