---
pool:
  name: default
  vmimage: ubuntu-20.04

trigger:
  - main
 
 steps:
  - task: Maven@3
    inputs:
      mavenPOMFile: 'pom.xml'
      goals: 'package'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkVersionOption: '1.17'
      jdkDirectory: /usr/lib/jvm/java-17-openjdk-amd64
      mavenVersionOption: 'Path'
      mavenDirectory: /home/p/apache-maven-3.9.0