---
- name: install utilities
  become: yes
  hosts: all
  vars:
    utils:
      - git
      - tree
      - nano
  tasks:
    - name: install utils
      ansible.builtin.apt:
        name: "{{ utils }}"
        state: present
      notify:
        - ensure ssh is running
  handlers:
    - name: ensure ssh is running
      ansible.builtin.systemd:
        name: sshd
        state: running