---
- name: Install Java
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: openjdk-16-jdk,openjdk-13-jdk,openjdk-17-jdk
        update_cache: yes
        state: present